#!/usr/bin/env ruby

require 'readline'

def match_one(pattern, text)
  # Everything matches the empty pattern
  if not pattern
    return true
  end

  # Empty text doesn't match non-empty patterns
  if not text
    return false
  end

  # The wildcard pattern matches everything
  if pattern == "."
    return true
  end

  return pattern == text
end

# Recursively match characters in the string
def match(pattern, text)
  # If the pattern is exhausted, the text matched
  if pattern == ""
    return true
  # We can match the end of strings with `$`
  elsif text == "" && pattern == "$"
    return true
  # `?` denotes optional single-character matches
  elsif pattern[1] == "?"
    return match_question(pattern, text)
  # `*` allows zero or more matches of the prior character
  elsif pattern[1] == "*"
    return match_star(pattern, text)
  end

  return match_one(pattern[0], text[0]) &&
         match(pattern[1..-1], text[1..-1])
end

# The `^` character restricts matching to the beginning of strings
def search(pattern, text)
  if pattern[0] == "^"
    return match(pattern[1..-1], text)
  end

  # The `.*` pattern allows the character to appear anywhere in the string
  # Leading characters that don't match are simply stripped
  return match(".*#{pattern}", text)
end

def match_question(pattern, text)
  # Check if the character before the `?` matches the text, and the
  # subsequent pattern
  if match_one(pattern[0], text[0]) and match(pattern[2..-1], text[1..-1])
    return true
  end

  # Otherwise, strip the optional and move on
  return match(pattern[2..-1], text)
end

def match_star(pattern, text)
  # If the first character matches, strip it and move on recursively
  if match_one(pattern[0], text[0]) && match(pattern, text[1..-1])
    return true
  end

  # Otherwise, advance past the pattern
  return match(pattern[2..-1], text)
end

def process_input(line)
  args = line.split(' ')
  if args[0].nil?
    args[0] = ""
  end
  if args[1].nil?
    args[1] = ""
  end

  return args[0], args[1]
end

if ARGV.size > 0
  contents = File.open(ARGV[0],"r").read.chomp
  lines = contents.split("\n")

  for line in lines
    begin
      pattern, text = process_input(line)
      p search(pattern, text)
    rescue => e
      puts "An error occured #{e.message}"
      return
    end
  end

  return
end

while buf = Readline.readline('>> ', true)
  begin
    pattern, text = process_input(buf)
    p search(pattern, text)
  rescue => e
    puts "An error occured #{e.message}"
  end
end
